All scripts modified.
I've modified all the scripts to make them POSIX compliant. Why? To make them portable, and because in Arch, /bin/sh is linked to Bash.

ls -l /usr/bin/sh

And according to the Arch Wiki, Dash is 35% to 40% faster than Bash, and I've made the change to link sh to dash.

But it's not something that will affect you; the functionality will remain the same. In fact, you may or may not update the scripts. I'm only uploading these changes so I don't have different code on my machine and in the repository, because I'm sure I'll forget in the future and mix up code, and to prevent that from happening.

diff --git a/misc/bin/colorscript b/misc/bin/colorscript
--- a/misc/bin/colorscript
+++ b/misc/bin/colorscript
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # Author: gh0stzk
 # Revision Date: 09.02.2025 10:00:58
 # Repository: https://github.com/gh0stzk/dotfiles
@@ -13,14 +13,12 @@
 # ----------------------------------------------------------------------------
 
 DIR_COLORSCRIPTS="$HOME/.local/share/asciiart"
-shopt -s nullglob
 
 # Load scripts into an array
-color_scripts=("$DIR_COLORSCRIPTS"/*)
-color_scripts=("${color_scripts[@]##*/}")  # Eliminar rutas, conservar nombres
-length_colorscripts=${#color_scripts[@]}
+color_scripts=$(ls "$DIR_COLORSCRIPTS" 2>/dev/null)
+length_colorscripts=$(printf '%s\n' "$color_scripts" | wc -l)
 
-function _help() {
+_help() {
     echo "Description: A collection of terminal color scripts."
     echo
     echo "Usage: colorscript [OPTION] [SCRIPT NAME/INDEX]"
@@ -32,34 +30,37 @@ function _help() {
         "-e" "Run a specified color script by NAME or INDEX."
 }
 
-function _list() {
+_list() {
     echo "There are $length_colorscripts installed color scripts:"
-    for i in "${!color_scripts[@]}"; do
-        printf "%d\t%s\n" "$((i+1))" "${color_scripts[i]}"
+    i=1
+    for script in $color_scripts; do
+        printf "%d\t%s\n" "$i" "$script"
+        i=$((i + 1))
     done
 }
 
-function _random() {
-    local random_index=$(( RANDOM % length_colorscripts ))
-    exec "${DIR_COLORSCRIPTS}/${color_scripts[random_index]}"
+_random() {
+    random_index=$(od -An -N2 -tu2 /dev/urandom | awk -v max="$length_colorscripts" '{print ($1 % max) + 1}')
+    chosen_script=$(printf '%s\n' $color_scripts | sed -n "${random_index}p")
+    exec "$DIR_COLORSCRIPTS/$chosen_script"
 }
 
-function _run_colorscript() {
-    local script_name
-    if [[ $1 =~ ^[0-9]+$ ]]; then  # If it is numerical
-        if (( $1 < 1 || $1 > length_colorscripts )); then
-            echo "Error: Invalid index '$1'. Use 1-$length_colorscripts." >&2
+_run_colorscript() {
+    input="$1"
+    if printf '%s\n' "$input" | grep -Eq '^[0-9]+$'; then
+        if [ "$input" -lt 1 ] || [ "$input" -gt "$length_colorscripts" ]; then
+            echo "Error: Invalid index '$input'. Use 1-$length_colorscripts." >&2
             exit 1
         fi
-        script_name="${color_scripts[$1-1]}"
-    else  # If it is name
-        if [[ ! -f "${DIR_COLORSCRIPTS}/$1" ]]; then
-            echo "Error: The '$1' script does not exist." >&2
+        script_name=$(printf '%s\n' $color_scripts | sed -n "${input}p")
+    else
+        if [ ! -f "$DIR_COLORSCRIPTS/$input" ]; then
+            echo "Error: The '$input' script does not exist." >&2
             exit 1
         fi
-        script_name="$1"
+        script_name="$input"
     fi
-    exec "${DIR_COLORSCRIPTS}/${script_name}"
+    exec "$DIR_COLORSCRIPTS/$script_name"
 }
 
 # Process arguments
